model_type: medsam2
medsam_root: /home/alex/Project/MRI/MedSAM2
config_name: configs/sam2.1_hiera_t512.yaml
checkpoint_path: /home/alex/Project/MRI/weights/MedSAM2_MRI_LiverLesion.pt
device: cuda
input_size: 512
layers:
  l1: 0
  l2: 1
  l3: 2
normalize_mode: zscore
